CREATE DATABASE SQLPulse
GO

USE [master]
GO
ALTER DATABASE [SQLPulse] MODIFY FILE ( NAME = N'SQLPulse', SIZE = 262144KB , FILEGROWTH = 131072KB )
GO
ALTER DATABASE [SQLPulse] MODIFY FILE ( NAME = N'SQLPulse_log', SIZE = 262144KB , FILEGROWTH = 131072KB )
GO